import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import GridItems from '@/components/GridItems'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products, setProducts] = useState([
    {
      "_id": "62fcf1c9d288ba297c7dd3c1",
      "featured": false,
      "rating": 4.6,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "bar stool",
      "price": 40,
      "company": "liddy",
      "__v": 0
  },
  {
      "_id": "62fcf1c9d288ba297c7dd3c4",
      "featured": true,
      "rating": 0,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "entertainment center",
      "price": 59,
      "company": "caressa",
      "__v": 0
  },
  {
      "_id": "62fcf1c9d288ba297c7dd3c5",
      "featured": true,
      "rating": 0,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "high-back bench",
      "price": 39,
      "company": "ikea",
      "__v": 0
  },
  {
      "_id": "62fcf1c9d288ba297c7dd3c6",
      "featured": false,
      "rating": 0,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "leather sofa",
      "price": 99,
      "company": "caressa",
      "__v": 0
  },
  {
      "_id": "62fcf1c9d288ba297c7dd3c8",
      "featured": false,
      "rating": 0,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "modern poster",
      "price": 30,
      "company": "liddy",
      "__v": 0
  },
  {
      "_id": "62fcf1c9d288ba297c7dd3ca",
      "featured": false,
      "rating": 0,
      "createdAt": "2022-08-17T13:48:45.542Z",
      "name": "simple chair",
      "price": 109,
      "company": "liddy",
      "__v": 0
  }
  ]) 
  return (
    <>
      <Head>
        <title>EcOmercer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      <GridItems products={products} />

         
      </main>
    </>
  )
}
