import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import GridItems from "@/components/GridItems";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ products }) {
  const [modal, setModal] = useState(false);
  const handleModal = () => {
    setModal(!modal);
  };
  const [productList, setProducts] = useState(products);

  return (
    <>
      <Head>
        <title>EcOmercer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button className="btn" onClick={handleModal}>
          filter
        </button>
        <GridItems productList={productList} />

        {modal && <Modal handleModal={handleModal} />}
      </main>
    </>
  );
}

const getAllProducts = async () => {
  const res = await fetch("http://localhost:3001/api/");
  const data = res.json();
  return data;
};

export async function getStaticProps() {
  const productList = await getAllProducts();
  return {
    props: {
      products: productList,
    },
  };
}
